version: "3.9"

services:
  web-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-web-analyzer
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
