services:
  web-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-web-analyzer
    ports:
      - "8080:8080"
      - "7070:7070"
    volumes:
      - ./logs:/app/logs

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - web-analyzer-network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - web-analyzer-network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  web-analyzer-network:
    driver: bridge


volumes:
  grafana_data: