{
 "title": "Web Analyzer",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes_total / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}